// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7bz-SanRM4W7qSXdHoOKSdQUxAc8IAjk',
    appId: '1:1095521958888:web:017c56692c8bb5cc2ac25d',
    messagingSenderId: '1095521958888',
    projectId: 'teraservus',
    authDomain: 'teraservus.firebaseapp.com',
    storageBucket: 'teraservus.appspot.com',
    measurementId: 'G-6DJ2N5LZWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRBZxOma64xmWoy6Qm1bTVJNclv56fwmE',
    appId: '1:1095521958888:android:ad2302cf72a869132ac25d',
    messagingSenderId: '1095521958888',
    projectId: 'teraservus',
    storageBucket: 'teraservus.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7bz-SanRM4W7qSXdHoOKSdQUxAc8IAjk',
    appId: '1:1095521958888:web:19fd6ae831cce3692ac25d',
    messagingSenderId: '1095521958888',
    projectId: 'teraservus',
    authDomain: 'teraservus.firebaseapp.com',
    storageBucket: 'teraservus.appspot.com',
    measurementId: 'G-S0SMCXL9QX',
  );
}
